language: c++

sudo: false

jobs:
  include:
    - stage: compile osx
      os: osx
      osx_image: xcode10.1
      env:
        - CMAKE_OPTIONS="-DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 -DBUILD_PYTHON_INTERFACE=ON"
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        draft: true
        skip_cleanup: true
        file: build/sdg-${TRAVIS_OS_NAME}.tar.gz
        on:
          tags: true
    - stage: compile linux
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz
            - lcov
            - r-base
            - r-base-dev
            - python3
            - python3-pip
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && GCOV=gcov-6 && DEPLOY=true"
        - CMAKE_OPTIONS="-DDOXYGEN_EXECUTABLE=${HOME}/bin/doxygen -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 -DBUILD_PYTHON_INTERFACE=ON -DBUILD_R_INTERFACE=OFF -DBUILD_COV=ON -DBUILD_DOC=ON"
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        draft: false
        skip_cleanup: true
        file: build/sdg-${TRAVIS_OS_NAME}.tar.gz
        on:
          tags: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs python3 gcc@6; git lfs install; fi
  - eval "${MATRIX_EVAL}"

before_script:
  - git lfs pull

script:
  - .travis/build.sh

install:
  - pip3 install --upgrade pip
  - export PATH="${HOME}"/Library/Python/3.7/bin:"${PATH}"
  - pip3 install --user virtualenv --upgrade
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install sphinx breathe recommonmark sphinx-rtd-theme sphinxcontrib-bibtex Pygments
  - .travis/install.sh

after_success:
  # Creating report
  - lcov --gcov-tool=gcov-6 --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --gcov-tool=gcov-6 --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --gcov-tool=gcov-6 --remove coverage.info '*deps*' --output-file coverage.info # filter out deps
  - lcov --gcov-tool=gcov-6 --remove coverage.info '*catch.hpp' --output-file coverage.info # filter out catch
  - lcov --gcov-tool=gcov-6 --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build/doc/sphinx
  on:
    branch: master
    condition: $DEPLOY = true
